version: "3.8"

services:
  book-service:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    networks:
      - cloud-computing-shared-network

networks:
  cloud-computing-shared-network:
    external: true