version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - cloud-computing-shared-network

networks:
  cloud-computing-shared-network:
    external: true

volumes:
  mongo_data:
