version: "3.8"

services:
  user-service:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - cloud-computing-shared-network

networks:
  cloud-computing-shared-network:
    external: true